twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        photo_directory: '/uploads/company'
        google_map_api: '%env(GOOGLE_MAP_API)%'
   

when@test:
    twig:
        strict_variables: true
