controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

kernel:
    resource: ../src/Kernel.php
    type: annotation

# app_index:
#     path: /
#     controller: App\Controller\HelloController::index
